services:
  samba:
    image: dperson/samba
    restart: unless-stopped
      #privileged: true
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - ./data/samba:/share
    environment:
      - USERID=1000
      - GROUPID=1000

# https://hub.docker.com/r/dperson/samba
# -s "<name;/path>[;browse;readonly;guest;users;admins;writelist;comment]"
#  required arg: "<name>;</path>"
#  <name> is how it's called for clients
#  <path> path to share
#  NOTE: for the default values, just leave blank
#  [browsable] default:'yes' or 'no'
#  [readonly] default:'yes' or 'no'
#  [guest] allowed default:'yes' or 'no'
#  NOTE: for user lists below, usernames are separated by ','
#  [users] allowed default:'all' or list of allowed users
#  [admins] allowed default:'none' or list of admin users
#  [writelist] list of users that can write to a RO share
#  [comment] description of share

    command: |
      -p
      -u "user1;pass1"
      -u "user2;pass2"
      -s "public;/share/public;yes;no;yes;;;;Public dir"
      -s "private;/share/private;yes;no;no;user1,user2;user1;user1;Private dir"
