services:
  gitea:
    image: gitea/gitea:1.23.3
    restart: unless-stopped
    ports:
      - "222:22"
      - "3000:3000"
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
